name: CI

on:
   workflow_dispatch:

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install curl grep

       - name: Build non-root variant
         run: |
          curl -OL https://github.com/kawinpattanai/revanced/releases/download/1.0/revanced-creator.keystore
          export additional_args="--keystore=revanced-creator.keystore"
          sh -c "$(curl https://raw.githubusercontent.com/kawinpattanai/revanced/main/patch.sh)"
          curl -OL https://github.com/kawinpattanai/revanced/releases/download/1.0/vanced-microg.apk

       - name: Upload Build Artifact(non-root)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-non-root
           path: |
            revanced-*-non-root.apk
            vanced-microg.apk

       - name: Build youtube-music variant
         run: |
          curl -OL https://github.com/kawinpattanai/revanced/releases/download/1.0/revanced-creator-music.keystore
          export additional_args="--keystore=revanced-creator-music.keystore"
          export what_to_patch="youtube-music"
          sh -c "$(curl https://raw.githubusercontent.com/kawinpattanai/revanced/main/patch.sh)"

       - name: Upload Build Artifact(YouTube-Music)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-music
           path: revanced-music-*-non-root.apk
